DjEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('',include('products.urls')),
    path('cart/',include('cart.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name ='cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-completed/', payment_completed, name='payment_completed'),
]

products/urls.py
from django.urls import path
from .views import *


app_name ='products'


urlpatterns = [
    path('', new_arrival, name='new_arrival'),
    path('products_page/', products_home, name='products_page'),
    path('product-detail/<int:id>', product_detail, name='product_detail'),
    path('add-to-cart/<int:id>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:id>', remove_from_cart, name='remove_from_cart'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import *
from account.models import Address
# Create your models here.



class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.item)

    def get_toatl_item_price(self):
        return self.quantity * self.item.price


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(Address, related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self):
        return str(self.user)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_toatl_item_price()
        return total

cart/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOOSE = (
    ('P', 'PayPal'),
)


class CheckOutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = CountryField(blank_label='(select country)').formfield(required=False,widget=CountrySelectWidget(attrs={'class': 'form-control',}))
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    street = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    apartment = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Appartment, suite, unit etc: (optional)'}))
    town = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    same_billing_addres = forms.BooleanField(widget=forms.CheckboxInput())
    save_info = forms.BooleanField(widget=forms.CheckboxInput())
    payment_option  = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOOSE)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.views.generic import View
from .forms import CheckOutForm
from django.contrib import messages
from account.models import Address
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def cart(request):
    try:
        order = get_object_or_404(Order, user=request.user, ordered=False)
        order_items = order.items.all()

        if request.method == 'POST':
            order_item_id = request.POST['order_item_id']
            order_item_quntity = request.POST['quantity']
            update_qty = get_object_or_404(OrderItem, id=order_item_id)
            update_qty.quantity = int(order_item_quntity)
            update_qty.save()

        context = {
            'order_items':order_items,
            'order':order,
        }
        return render(request, 'cart/cart.html', context)
    except :
        return render(request, 'cart/cart.html')
    return render(request, 'cart/cart.html', context)



class CheckOutView(View):
    def get(self, *args, **kwargs):
        try:
            order = get_object_or_404(Order, user=self.request.user, ordered=False)
            form = CheckOutForm()
            context = {
                'form':form,
                'order':order,
            }
            return render(self.request, 'cart/checkout.html', context)
        except:
            return redirect('cart:cart')

    def post(self, *args, **kwargs):
        form = CheckOutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                first_name = form.cleaned_data.get('first_name')
                last_name = form.cleaned_data.get('last_name')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                phone = form.cleaned_data.get('phone')
                street = form.cleaned_data.get('street')
                apartment = form.cleaned_data.get('apartment')
                town = form.cleaned_data.get('town')
                email = form.cleaned_data.get('email')
                same_billing_addres = form.cleaned_data.get('same_billing_addres')
                save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')
                billing_addres = Address(
                    user = self.request.user,
                    first_name = first_name,
                    last_name = last_name,
                    phone = phone,
                    street_address = street,
                    apartment_address = apartment,
                    town = town,
                    email = email,
                    country = country,
                    zip = zip,
                    address_type = 'B',

                )
                billing_addres.save()
                order.billing_address = billing_addres
                order.save()
                return redirect('cart:payment')

            messages.warning(self.request, 'Failed To CheckOut')
            return redirect('cart:checkout')
        except ObjectDoesNotExist:
            messages.info(self.request, "You do not have an active order")
            return redirect("cart:checkout")



def payment(request):
    try:
        order = get_object_or_404(Order, user=request.user, ordered=False)

        context = {
            'order':order,
        }

        return render(request, 'cart/payment.html', context)
    except:
        return redirect('cart:cart')



def payment_completed(request):
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        order.ordered = True
        order.save()

        for order_item in order.items.all():
            order_item.ordered = True
            order_item.save()

        messages.warning(request, 'Payment successfully done..')
        return render(request, 'cart/payment_done.html')

    except:
        messages.warning(request, 'Payment failed..')
        return redirect('cart:cart')


    messages.warning(request, 'Something went wrong..')
    return render(request, 'cart/payment_done.html')

cart/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}


<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
            {% if messages %}
              <div class="alert alert-success" role="alert">
                {% for message in messages %}
                  <p>{{ message }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Product</th>
						        <th>Price</th>
						        <th>Quantity</th>
                    <th></th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
                  {% for order_item in order_items %}
  						      <tr class="text-center">
  						        <td class="product-remove"><a href="{% url 'products:remove_from_cart' order_item.item.id %}"><span class="ion-ios-close"></span></a></td>

  						        <td class="image-prod"><div class="img" style="background-image:url({{order_item.item.image.url}});"></div></td>

  						        <td class="product-name">
  						        	<h3>{{order_item.item.product_name}}</h3>
  						        	<p>Far far away, behind the word mountains, far from the countries</p>
  						        </td>

  						        <td class="price">${{order_item.item.price}}</td>
                      <form class="" action="{% url 'cart:cart' %}" method="post">
                        {% csrf_token %}
      						        <td class="quantity">

        						        	<div class="input-group mb-3">
                                  <input type="number" name="quantity" id="quantity" class="quantity form-control input-number" value="{{order_item.quantity}}" min="1" max="100">
                                  <input type="hidden" name="order_item_id" value="{{order_item.id}}">
        					          	</div>

      					          </td>

                          <td class="product-remove">
                            <button type="submit" name="button"><span class="ion-ios-refresh"></span></button>
                          </td>
                      </form>

  						        <td class="total">${{order_item.get_toatl_item_price}}</td>
  						      </tr>
                  {% endfor %}
                  <!-- END TR-->


						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-start">
    			<div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Cart Totals</h3>
    					<p class="d-flex">
    						<span>Subtotal</span>
    						<span>${{order.get_total}}</span>
    					</p>
    					<p class="d-flex">
    						<span>Delivery</span>
    						<span>$0.00</span>
    					</p>
    					<p class="d-flex">
    						<span>Discount</span>
    						<span>$3.00</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>${{order.get_total}}</span>
    					</p>

    				</div>
    				<p class="text-center"><a href="{% url 'cart:checkout' %}" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
    			</div>
    		</div>
			</div>
		</section>



{%endblock%}

cart/templates/cart/checkout.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}

{% load crispy_forms_tags %}

<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Checkout</span></p>
        <h1 class="mb-0 bread">Checkout</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-10 ftco-animate">

        {% if messages %}
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Thank You!</h4>
            {% for message in messages %}
              <p>{{ message }}</p>
            {% endfor %}
          </div>
        {% endif %}


        <form action="#" class="billing-form" method="post">
          {% csrf_token %}
          <h3 class="mb-4 billing-heading">Billing Details</h3>
          <div class="row align-items-end">
            <div class="col-md-6">
              <div class="form-group">
                <label for="firstname">Firt Name</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.first_name}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="lastname">Last Name</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.last_name}}
              </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-12">
              <div class="form-group">
                <label for="country">State / Country</label>
                <div class="select-wrap">
                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                    {{ form.country }}
                </div>
              </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="streetaddress">Street Address</label>
                <!-- <input type="text" class="form-control" placeholder="House number and street name"> -->
                {{form.street}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <!-- <input type="text" class="form-control" placeholder="Appartment, suite, unit etc: (optional)"> -->
                {{form.apartment}}
              </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="towncity">Town / City</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.town}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="postcodezip">Postcode / ZIP *</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.zip}}
              </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="phone">Phone</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.phone}}
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="emailaddress">Email Address</label>
                <!-- <input type="text" class="form-control" placeholder=""> -->
                {{form.email}}
              </div>
            </div>
            <div class="w-100"></div>
            <div class="col-md-12">
              <div class="form-group mt-4">
                <div class="radio">
                  <label class="mr-3">{{form.same_billing_addres}} Same billing addres? </label>
                  <label>{{form.save_info}} Save info</label>
                </div>
              </div>
            </div>
          </div>

          <div class="row mt-5 pt-3 d-flex">
            <div class="col-md-6 d-flex">
                <div class="cart-detail cart-total bg-light p-3 p-md-4">
                  <h3 class="billing-heading mb-4">Cart Total</h3>
                  <p class="d-flex">
                    <span>Subtotal</span>
                    <span>${{order.get_total}}</span>
                  </p>
                  <p class="d-flex">
                    <span>Delivery</span>
                    <span>$0.00</span>
                  </p>
                  <p class="d-flex">
                    <span>Discount</span>
                    <span>$0.00</span>
                  </p>
                  <hr>
                  <p class="d-flex total-price">
                    <span>Total</span>
                    <span>${{order.get_total}}</span>
                  </p>
                </div>

            </div>
            <div class="col-md-6">
              <div class="cart-detail bg-light p-3 p-md-4">
                <h3 class="billing-heading mb-4">Payment Method</h3>

                <div class="form-group">
                  <div class="col-md-12">
                    <div class="radio">
                       <label>{{form.payment_option}}</label>
                    </div>
                  </div>
                </div>

                <p><button type='submit' class="btn btn-primary py-3 px-4">Place an order</button></p>
              </div>
            </div>
          </div>
        </form><!-- END -->




      </div> <!-- .col-md-8 -->
    </div>
  </div>
</section> <!-- .section -->


{%endblock%}

cart/templates/cart/payment.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}

<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-10 ftco-animate">

        <!-- Set up a container element for the button -->
           <div id="paypal-button-container"></div>

           <!-- Include the PayPal JavaScript SDK -->
           <script src="https://www.paypal.com/sdk/js?client-id=AeF6pgYqDfyEhhesP9rrv6zHzdhNU3ohUPBHIN2Iy83DVCPW1Sg8zfqkfu7AC7GgVrC7mX7av3Cj_F_c&disable-funding=credit,card"></script>

           <script>
               // Render the PayPal button into #paypal-button-container
               paypal.Buttons({

                   // Set up the transaction
                   createOrder: function(data, actions) {
                       return actions.order.create({
                           purchase_units: [{
                               amount: {
                                   value: '{{order.get_total}}'
                               }
                           }]
                       });
                   },

                   // Finalize the transaction
                   onApprove: function(data, actions) {
                       return actions.order.capture().then(function(orderData) {
                           // Successful capture! For demo purposes:
                           console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                           var transaction = orderData.purchase_units[0].payments.captures[0];
                           alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                           window.location.href = "{% url 'cart:payment_completed' %}"

                           // Replace the above to show a success message within this page, e.g.
                           // const element = document.getElementById('paypal-button-container');
                           // element.innerHTML = '';
                           // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                           // Or go to another URL:  actions.redirect('thank_you.html');
                       });
                   }


               }).render('#paypal-button-container');
           </script>
      </div>
    </div>
  </div>

</section>

{%endblock%}

cart/templates/cart/payment_done.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}

<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-10 ftco-animate">

        {% if messages %}
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Thank You!</h4>
            {% for message in messages %}
              <p>{{ message }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>

</section>

{%endblock%}