DjEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('',include('products.urls')),
    path('cart/',include('cart.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name ='cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-completed/', payment_completed, name='payment_completed'),
]

products/urls.py
from django.urls import path
from .views import *


app_name ='products'


urlpatterns = [
    path('', new_arrival, name='new_arrival'),
    path('products_page/', products_home, name='products_page'),
    path('product-detail/<int:id>', product_detail, name='product_detail'),
    path('add-to-cart/<int:id>', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:id>', remove_from_cart, name='remove_from_cart'),
]

products/models.py
from django.db import models

# Create your models here
class Category(models.Model):
    category_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(blank=True, max_length=255)
    cat_image = models.ImageField(blank=True, upload_to='photos/categories')

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name





class Product(models.Model):
    product_name = models.CharField(max_length=125)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=19, decimal_places=2)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    stock = models.IntegerField(default=1)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, related_name='product_cat',  on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.product_name

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from cart.models import *
from django.contrib import messages
from django.core.paginator import Paginator
from .filters import ProductFilter


# Create your views here.
@login_required(login_url = 'account:login')
def new_arrival(request):
    return render(request, 'products/new_arrival_products.html')






@login_required(login_url = 'account:login')
def products_home(request):

    all_category = Category.objects.all()


    if request.method == 'POST':
        if 'search_product' in request.POST:
            search = request.POST['search_product']
            if search != '':
                all_products_fashion = Product.objects.filter(product_name__icontains=search)
            else:
                all_products_fashion = Product.objects.all()
    else:
        all_products_fashion = Product.objects.all()
        all_products_filter = ProductFilter(request.GET, queryset=all_products_fashion)
        all_products_fashion = all_products_filter.qs
        print(all_products_fashion)
    page_num = request.GET.get('page', 1)
    paginator = Paginator(all_products_fashion, 12)

    try:
        all_products_fashion = paginator.page(page_num)
    except PageNotAnInteger:
        all_products_fashion = paginator.page(1)
    except EmptyPage:
        all_products_fashion = paginator.page(paginator.num_pages)


    context = {
        'all_products_fashion':all_products_fashion,
        'all_category':all_category,
        'all_products_filter':all_products_filter,
    }
    return render(request, 'products/products_home.html', context)




@login_required(login_url = 'account:login')
def product_detail(request, id):
    single_product = get_object_or_404(Product, id=id)


    if request.method == 'POST':
        product_id = request.POST['product_id']
        product_quntity = request.POST['quantity']


        try:
            item = get_object_or_404(Product, id=product_id)
            order_item, created = OrderItem.objects.get_or_create(
                item=item,
                user = request.user,
                ordered = False

            )

            if created:
                order_item.quantity = int(product_quntity)
                order_item.save()


            order_qs = Order.objects.filter(user=request.user, ordered=False)
            if order_qs.exists():
                order = order_qs[0]
                #check if order item in the order
                if order.items.filter(item__id=item.id).exists():
                    order_item.quantity += int(product_quntity)
                    order_item.save()
                    messages.info(request, 'This item quantity was updated to your cart')
                else:
                    messages.info(request, 'This item was added to your cart')
                    order.items.add(order_item)
                    order_item.quantity = int(product_quntity)
                    order_item.save()
            else:
                order = Order.objects.create(user=request.user)
                order.items.add(order_item)
                messages.info(request, 'This item was added to your cart')
        except Exception as e:
            print(e)

    context = {
        'single_product':single_product,
    }

    return render(request, 'products/product_detail.html', context)






def add_to_cart(request, id):
    item = get_object_or_404(Product, id=id)
    order_item, _ = OrderItem.objects.get_or_create(
        item=item,
        user = request.user,
        ordered = False

    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        #check if order item in the order
        if order.items.filter(item__id=item.id).exists():
            order_item.quantity += 1
            order_item.save()
        else:
            order.items.add(order_item)
    else:
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
    return redirect('products:products_page')








def remove_from_cart(request, id):
    item = get_object_or_404(Product, id=id)
    order_qs = Order.objects.filter(
        user = request.user,
        ordered = False

    )
    if order_qs.exists():
        order = order_qs[0]
        #check if order item in the order
        if order.items.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.filter(
                item = item,
                user = request.user,
                ordered = False
            )[0]
            order.items.remove(order_item)
            messages.info(request, 'This item was removed from your cart')
            return redirect('cart:cart')
        else:
            messages.info(request, 'This item was not in  your cart')
            return redirect('cart:cart')
    else:
        messages.info(request, 'You do not have an activate order')
        return redirect('cart:cart')

products/templates/products/product_detail.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}

<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Shop</span></p>
            <h1 class="mb-0 bread">Shop</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row">
    			<div class="col-lg-6 mb-5 ftco-animate">
    				<a href="#" class="image-popup prod-img-bg"><img src="{{ single_product.image.url }}" class="img-fluid" alt="Colorlib Template"></a>
    			</div>
    			<div class="col-lg-6 product-details pl-md-5 ftco-animate">
    				<h3>{{ single_product.product_name }}</h3>
    				<div class="rating d-flex">
							<p class="text-left mr-4">
								<a href="#" class="mr-2">5.0</a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
							</p>
							<p class="text-left mr-4">
								<a href="#" class="mr-2" style="color: #000;">100 <span style="color: #bbb;">Rating</span></a>
							</p>
							<p class="text-left">
								<a href="#" class="mr-2" style="color: #000;">500 <span style="color: #bbb;">Sold</span></a>
							</p>
						</div>
    				<p class="price"><span>${{ single_product.price }}</span></p>
    				<p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
    				<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.
						</p>
						<div class="row mt-4">
              <form class="" action="{%  url 'products:product_detail' single_product.id %}" method="post">
                {% csrf_token %}
  							<div class="col-md-6">
  								<div class="form-group d-flex">
  		              <div class="select-wrap">
  	                  <div class="icon"><span class="ion-ios-arrow-down"></span></div>
  	                  <select name="" id="" class="form-control">
  	                  	<option value="">Small</option>
  	                    <option value="">Medium</option>
  	                    <option value="">Large</option>
  	                    <option value="">Extra Large</option>
  	                  </select>
  	                </div>
  		            </div>
  							</div>

                <div class="row mt-2">
    							<div class="col-md-8">
    								<div class="form-group">


                        <input type="hidden" id="product_id" name="product_id" class="quantity form-control input-number" value="{{single_product.id}}">
                        <input type="number" id="quantity" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">


    		            </div>
    							</div>


  	          	<div class="w-100"></div>
  	          	<div class="col-md-12">
  	          		<p style="color: #000;">80 piece available</p>
  	          	</div>
            	</div>
            	<p><input type="submit" value="Add to Cart" class="btn btn-primary py-3 px-5">   <a href="cart.html" class="btn btn-primary py-3 px-5">Buy now</a></p>


            </form>
    			</div>
    		</div>




    		<div class="row mt-5">
          <div class="col-md-12 nav-link-wrap">
            <div class="nav nav-pills d-flex text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
              <a class="nav-link ftco-animate active mr-lg-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Description</a>

              <a class="nav-link ftco-animate mr-lg-1" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Manufacturer</a>

              <a class="nav-link ftco-animate" id="v-pills-3-tab" data-toggle="pill" href="#v-pills-3" role="tab" aria-controls="v-pills-3" aria-selected="false">Reviews</a>

            </div>
          </div>
          <div class="col-md-12 tab-wrap">

            <div class="tab-content bg-light" id="v-pills-tabContent">

              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="day-1-tab">
              	<div class="p-4">
	              	<h3 class="mb-4">{{ single_product.product_name }}</h3>
	              	<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
              	</div>
              </div>

              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-day-2-tab">
              	<div class="p-4">
	              	<h3 class="mb-4">Manufactured By Nike</h3>
	              	<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
              	</div>
              </div>
              <div class="tab-pane fade" id="v-pills-3" role="tabpanel" aria-labelledby="v-pills-day-3-tab">
              	<div class="row p-4">
						   		<div class="col-md-7">
						   			<h3 class="mb-4">23 Reviews</h3>
						   			<div class="review">
								   		<div class="user-img" style="background-image: url(images/person_1.jpg)"></div>
								   		<div class="desc">
								   			<h4>
								   				<span class="text-left">Jacob Webb</span>
								   				<span class="text-right">14 March 2018</span>
								   			</h4>
								   			<p class="star">
								   				<span>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
							   					</span>
							   					<span class="text-right"><a href="#" class="reply"><i class="icon-reply"></i></a></span>
								   			</p>
								   			<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>
								   		</div>
								   	</div>
								   	<div class="review">
								   		<div class="user-img" style="background-image: url(images/person_2.jpg)"></div>
								   		<div class="desc">
								   			<h4>
								   				<span class="text-left">Jacob Webb</span>
								   				<span class="text-right">14 March 2018</span>
								   			</h4>
								   			<p class="star">
								   				<span>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
							   					</span>
							   					<span class="text-right"><a href="#" class="reply"><i class="icon-reply"></i></a></span>
								   			</p>
								   			<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>
								   		</div>
								   	</div>
								   	<div class="review">
								   		<div class="user-img" style="background-image: url(images/person_3.jpg)"></div>
								   		<div class="desc">
								   			<h4>
								   				<span class="text-left">Jacob Webb</span>
								   				<span class="text-right">14 March 2018</span>
								   			</h4>
								   			<p class="star">
								   				<span>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
								   					<i class="ion-ios-star-outline"></i>
							   					</span>
							   					<span class="text-right"><a href="#" class="reply"><i class="icon-reply"></i></a></span>
								   			</p>
								   			<p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrov</p>
								   		</div>
								   	</div>
						   		</div>
						   		<div class="col-md-4">
						   			<div class="rating-wrap">
							   			<h3 class="mb-4">Give a Review</h3>
							   			<p class="star">
							   				<span>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					(98%)
						   					</span>
						   					<span>20 Reviews</span>
							   			</p>
							   			<p class="star">
							   				<span>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					(85%)
						   					</span>
						   					<span>10 Reviews</span>
							   			</p>
							   			<p class="star">
							   				<span>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					(98%)
						   					</span>
						   					<span>5 Reviews</span>
							   			</p>
							   			<p class="star">
							   				<span>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					(98%)
						   					</span>
						   					<span>0 Reviews</span>
							   			</p>
							   			<p class="star">
							   				<span>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					<i class="ion-ios-star-outline"></i>
							   					(98%)
						   					</span>
						   					<span>0 Reviews</span>
							   			</p>
							   		</div>
						   		</div>
						   	</div>
              </div>
            </div>
          </div>
        </div>
    	</div>
    </section>


{%endblock%}

products/templates/products/products_home.html
{% extends 'base/base.html' %}
{% load static %}
{%block title%}
products home
{%endblock%}
{%block css%}
{%endblock%}
{%block content%}

<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Shop</span></p>
            <h1 class="mb-0 bread">Shop</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8 col-lg-10 order-md-last">
    				<div class="row">
              {% for product in all_products_fashion %}
  		    			<div class="col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex">
  		    				<div class="product d-flex flex-column">
  		    					<a href="#" class="img-prod"><img class="img-fluid" src="{{product.image.url}}" alt="Colorlib Template">
  		    						<div class="overlay"></div>
  		    					</a>
  		    					<div class="text py-3 pb-4 px-3">
  		    						<div class="d-flex">
  		    							<div class="cat">
  				    						<span>{{product.category.category_name}}</span>
  				    					</div>
  				    					<div class="rating">
  			    							<p class="text-right mb-0">
  			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
  			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
  			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
  			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
  			    								<a href="#"><span class="ion-ios-star-outline"></span></a>
  			    							</p>
  			    						</div>
  			    					</div>
  		    						<h3><a href="#">{{product.product_name}}</a></h3>
  		    						<div class="pricing">
  			    						<p class="price"><span>${{product.price}}</span></p>
  			    					</div>
  			    					<p class="bottom-area d-flex px-3">
  		    							<a href="{% url 'products:add_to_cart' product.id %}" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
  		    							<a href="{% url 'products:product_detail' product.id %}" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
  		    						</p>
  		    					</div>
  		    				</div>
  		    			</div>
              {% endfor %}

		    		</div>
		    		<div class="row mt-5">
		          <div class="col text-center">
		            <div class="block-27">
                  <span class="step-links">
                      {% if all_products_fashion.has_previous %}
                          <a href="?page=1">&laquo; first</a>
                          <a href="?page={{ all_products_fashion.previous_page_number }}">previous</a>
                      {% endif %}

                      <span class="current">
                          Page {{ all_products_fashion.number }} of {{ all_products_fashion.paginator.num_pages }}.
                      </span>

                      {% if all_products_fashion.has_next %}
                          <a href="?page={{ all_products_fashion.next_page_number }}">next</a>
                          <a href="?page={{ all_products_fashion.paginator.num_pages }}">last &raquo;</a>
                      {% endif %}
                  </span>

		            </div>
		          </div>
		        </div>
		    	</div>

          <div class="sidebar-box">
            <form class="search-form" method="post">
              {% csrf_token %}
              <div class="form-group">
                <span class="icon ion-ios-search"></span>
                <input type="text" class="form-control" name='search_product' placeholder="Type a keyword and hit enter">
              </div>
              <div align="center">
                <button type="submit" class="btn btn-primary py-2 px-3">Search</button>
              </div>

            </form>
          </div>

		    	<div class="col-md-4 col-lg-2">

		    		<div class="sidebar">
							<div class="sidebar-box-2">
								<h2 class="heading">Categories</h2>
								<div class="fancy-collapse-panel">
                  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                     <div class="panel panel-default">
                         <div class="panel-heading" role="tab" id="headingOne">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Men's Shoes
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                             <div class="panel-body">
                                 <ul>
                                 	<li><a href="#">Sport</a></li>
                                 	<li><a href="#">Casual</a></li>
                                 	<li><a href="#">Running</a></li>
                                 	<li><a href="#">Jordan</a></li>
                                 	<li><a href="#">Soccer</a></li>
                                 	<li><a href="#">Football</a></li>
                                 	<li><a href="#">Lifestyle</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading" role="tab" id="headingTwo">
                             <h4 class="panel-title">
                                 <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Women's Shoes
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                             <div class="panel-body">
                                <ul>
                                 	<li><a href="#">Sport</a></li>
                                 	<li><a href="#">Casual</a></li>
                                 	<li><a href="#">Running</a></li>
                                 	<li><a href="#">Jordan</a></li>
                                 	<li><a href="#">Soccer</a></li>
                                 	<li><a href="#">Football</a></li>
                                 	<li><a href="#">Lifestyle</a></li>
                                </ul>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading" role="tab" id="headingThree">
                             <h4 class="panel-title">
                                 <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Accessories
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                             <div class="panel-body">
                                <ul>
                                 	<li><a href="#">Jeans</a></li>
                                 	<li><a href="#">T-Shirt</a></li>
                                 	<li><a href="#">Jacket</a></li>
                                 	<li><a href="#">Shoes</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading" role="tab" id="headingFour">
                             <h4 class="panel-title">
                                 <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseThree">Clothing
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                             <div class="panel-body">
                                <ul>
                                 	<li><a href="#">Jeans</a></li>
                                 	<li><a href="#">T-Shirt</a></li>
                                 	<li><a href="#">Jacket</a></li>
                                 	<li><a href="#">Shoes</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                  </div>
               </div>
							</div>
							<div class="sidebar-box-2">
								<h2 class="heading">Price Range</h2>
	
                <form method="get">
                  {{ all_products_filter.form.as_p }}
                  <button type="submit" class="btn btn-primary py-2 px-3">Search</button>
              </form>
							</div>
						</div>
    			</div>
    		</div>
    	</div>
    </section>



{%endblock%}